### ISSUE TITLE
InyushinKominarShepelevPI42

### ISSUE THREAD

**Issue by hvorovk** [SergeyStaroletov/vertify18#1]
Если после добавления всех данных попытаться добавить билет и в окне добавления нажать "узнать цену", программа падает без каких либо окон, перед этим зависает. Да а еще цена в Double хранится.

![image](https://user-images.githubusercontent.com/10532514/36069469-10be9738-0f1d-11e8-98f1-fe4357180249.png)

**Comment by Venomkol** [comment]
Ошибка возникала при добавлении билета, когда нет свободных мест. Возможность добавления билета отключалась, но не отключалась возможность узнать цену билета, которая зависела от выбранного места, поэтому программа зацикливалась и выдавала исключение.
Цена в Double - это не баг, это фича.
![fix_bug](https://user-images.githubusercontent.com/14237222/36074700-69ade070-0f76-11e8-9b3b-89b56c811e61.png)

**Comment by hvorovk** [comment]
Если после добавления всех данных попытаться добавить билет и в окне добавления нажать "узнать цену", программа падает без каких либо окон, перед этим зависает. 
Ожидалось:
Либо заблокированая кнопка "узнать цену" или сообщение об ошибке
Реальность:
Программа намертво зависает.
